# Generated by Django 5.0.6 on 2024-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
