services:
  database:
    image: "postgres:16"
    container_name: online_school_database
    ports:
      - "5435:5432"   # Внешний порт:Внутренний порт
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  api_online_school:
    build:
      context: .
      dockerfile: Dockerfile
    image: online_school
    container_name: online_school_api
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    depends_on:
      - database
    volumes:
      - ./:/app/

volumes:
  pg_data:
